// <auto-generated />
using Final_Project_CIDM3312.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Final_Project_CIDM3312.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260510221842_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("Final_Project_CIDM3312.Models.Character", b =>
                {
                    b.Property<int>("CharacterID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PlayerID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("StatsID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("XP")
                        .HasColumnType("INTEGER");

                    b.HasKey("CharacterID");

                    b.HasIndex("StatsID");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("Final_Project_CIDM3312.Models.Player", b =>
                {
                    b.Property<int>("PlayerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CharacterID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Currency")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PlayerID");

                    b.HasIndex("CharacterID");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("Final_Project_CIDM3312.Models.Stats", b =>
                {
                    b.Property<int>("StatsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Agility")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CharacterID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Health")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Intelligence")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Luck")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mana")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Strength")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Willpower")
                        .HasColumnType("INTEGER");

                    b.HasKey("StatsID");

                    b.ToTable("Statss");
                });

            modelBuilder.Entity("Final_Project_CIDM3312.Models.Character", b =>
                {
                    b.HasOne("Final_Project_CIDM3312.Models.Stats", null)
                        .WithMany("Characters")
                        .HasForeignKey("StatsID");
                });

            modelBuilder.Entity("Final_Project_CIDM3312.Models.Player", b =>
                {
                    b.HasOne("Final_Project_CIDM3312.Models.Character", null)
                        .WithMany("Players")
                        .HasForeignKey("CharacterID");
                });

            modelBuilder.Entity("Final_Project_CIDM3312.Models.Character", b =>
                {
                    b.Navigation("Players");
                });

            modelBuilder.Entity("Final_Project_CIDM3312.Models.Stats", b =>
                {
                    b.Navigation("Characters");
                });
#pragma warning restore 612, 618
        }
    }
}
